[package]
name = "raspos"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kernel"
path = "src/main.rs"

[dependencies]
lock_api = { version = "0.4.5", features = ["nightly"] }

[target.'cfg(target_arch = "aarch64")'.dependencies]
tock-registers = "0.7.0"
cortex-a = "6.1.0"

[profile.release]
lto = true
