[tasks.asm]
command = "cargo"
args = ["objdump", "--release", "--", "-Cdtlg", "--section-headers"]

[tasks.nm]
command = "cargo"
args = ["nm", "--release", "--", "--print-size", "--size-sort", "--demangle"]

[tasks.kernel]
command = "cargo"
args = ["objcopy", "--release", "--", "--strip-all", "-O", "binary", "./target/kernel.img"]

[tasks.docker_build]
command = "docker"
args = ["build", "--tag", "raspos", "."]
dependencies = ["kernel"]

[tasks.docker]
command = "docker"
args = ["run", "--rm", "--name", "raspos", "raspos"]
dependencies = ["build"]

[tasks.cargo_clean]
command = "cargo"
args = ["clean"]

[tasks.docker_stop]
command = "docker"
args = ["stop", "raspos"]

[tasks.clean]
dependencies = ["cargo_clean", "docker_stop"]
