[tasks.asm]
command = "cargo"
args = ["objdump", "--release", "--", "-Cdtlg", "--section-headers"]

[tasks.nm]
command = "cargo"
args = ["nm", "--release", "--", "--print-size", "--size-sort", "--demangle"]

[tasks.kernel]
command = "cargo"
args = ["objcopy", "--release", "--", "--strip-all", "-O", "binary", "./target/kernel.img"]

[tasks.qemu]
command = "qemu-system-aarch64"
args = ["-M", "raspi3", "-serial", "stdio", "-display", "none", "-kernel", "./target/kernel.img"]
dependencies = ["kernel"]

[tasks.clean]
command = "cargo"
args = ["clean"]
