[tasks.asm]
command = "rust-objdump"
install_crate = { crate_name = "cargo-binutils", binary = "rust-objdump", test_arg = "--help" }
args = ["-Cdtlg", "--section-headers", "target/${CARGO_MAKE_CRATE_TARGET_TRIPLE}/release/kernel"]
dependencies = ["build-release"]

[tasks.nm]
command = "cargo"
args = ["nm", "--release", "--", "--print-size", "--size-sort", "--demangle"]

[tasks.kernel]
command = "cargo"
args = ["objcopy", "--release", "--", "--strip-all", "-O", "binary", "./target/kernel.img"]

[tasks.qemu]
command = "qemu-system-aarch64"
args = ["-M", "raspi3", "-serial", "stdio", "-display", "none", "-kernel", "./target/kernel.img"]
dependencies = ["kernel"]

[tasks.clean]
command = "cargo"
args = ["clean"]
