[build]
target = "src/arch/x86_64/x86_64-unknown-none.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true

[profile.test]
panic = "unwind"

[target.x86_64-unknown-none]
runner = "bootimage runner"

[target.thumbv7em-none-eabihf]
rustflags = []

[target.aarch64-unknown-none-softfloat]
rustflags = ["-Clink-arg=-Tsrc/arch/aarch64/link.ld"]
